update repo ...

diff --git a/bin/bl-conky-pipemenu b/bin/bl-conky-pipemenu
--- a/bin/bl-conky-pipemenu
+++ b/bin/bl-conky-pipemenu
@@ -1,9 +1,44 @@
 #!/bin/bash
+#    bl-conky-pipemenu - an Openbox pipemenu for manipulating conky
+#    Copyright (C) 2015 damo <damo@bunsenlabs.org>
 #
-# bl-conky-pipemenu
-# Written for BunsenLabs Linux by damo <damo@bunsenlabs.org> April 2015
+#    This program is free software: you can redistribute it and/or modify
+#    it under the terms of the GNU General Public License as published by
+#    the Free Software Foundation, either version 3 of the License, or
+#    (at your option) any later version.
+#
+#    This program is distributed in the hope that it will be useful,
+#    but WITHOUT ANY WARRANTY; without even the implied warranty of
+#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+#    GNU General Public License for more details.
+#
+#    You should have received a copy of the GNU General Public License
+#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-BL_COMMON_LIBDIR='/usr/lib/bunsen/bunsen-common'
+HELP='    bl-conky-pipemenu an Openbox Pipe Menu for use with conky
+    It should normally be called from an openbox menu.
+
+Options:
+    -h --help   show this message
+
+    If bl-conky-pipemenu is called with no options (the usual method),
+    it will output an xml openbox pipemenu for handling conky sessions.
+
+See /usr/share/bunsen/docs/helpfile-conkyzen.txt and "man conky"
+for more information.
+'
+# look for a help option somewhere
+for i in "$@"
+do
+    case "$i" in
+    -h|--help)
+        echo "$HELP"
+        exit 0
+        ;;
+    esac
+done
+
+BL_COMMON_LIBDIR='/usr/lib/bunsen/common'
 
 CONKYDEFAULT="$HOME/.conkyrc"
 CONKYPATH="$HOME/.config/conky"
@@ -11,50 +46,91 @@ CSESSIONFILE="$CONKYPATH/conky-sessionfile"
 SESSIONS="$CONKYPATH/saved-sessions"
 CZEN="bl-conkyzen"
 CSESSION="bl-conky-session"
-HELPFILE="/usr/share/bunsen/bunsen-docs/helpfile-conkyzen.txt"
+HELPFILE="/usr/share/bunsen/docs/helpfile-conkyzen.txt"
 
 if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
-    echo $"Error: Failed to locate bl-include.cfg in $BL_COMMON_LIBDIR" >&2
+    echo "Error: Failed to source bl-include.cfg in $BL_COMMON_LIBDIR" >&2
     exit 1
 fi
 if [ ! -e "$CSESSIONFILE" ] 2> /dev/null ; then
-    echo $"Error: Failed to locate conky-sessionfile in $CONKYPATH" >&2
+    echo "Error: Failed to locate conky-sessionfile in $CONKYPATH" >&2
     echo "conky -c $HOME/.conkyrc & sleep 1" > "$CSESSIONFILE"
 fi
 if [ ! -e "$SESSIONS" ] 2> /dev/null ; then
-    echo $"Error: Failed to locate saved-sessions in $CONKYPATH" >&2
+    echo "$0: Failed to locate saved-sessions in $CONKYPATH" >&2
 fi
+
+declareDependencies yad
 
 getSessions(){  # read any saved sessions from save-sessions file
     menuItem "Default" "$CSESSION $CSESSIONFILE"
-    while read session ;do
-        [[ -z $session ]] && continue   # skip if line is blank
-        menuItem "$session" "$CSESSION $session"
-    done < "$SESSIONS"
+    if [ -e "$SESSIONS" ]
+    then
+        while read -r session ;do
+            [[ -z $session ]] && continue   # skip if line is blank
+            menuItem "$session" "$CSESSION $session"
+        done < "$SESSIONS"
+    else
+        echo "$0: Failed to locate saved-sessions in $CONKYPATH" >&2
+    fi
 }
 
-loadEditmenu(){
+loadChooserMenu(){
+    if type "$CZEN" &>/dev/null;then  # bl-conkyzen script found
+        menuItem "Conky Chooser" "$CZEN"
+    fi
+}
+
+loadNewsessionMenu(){
+    if type "$CZEN" &>/dev/null;then  # bl-conkyzen script found
+        menuItem "New Conky Session" "$CZEN -z"
+    fi
+}
+
+loadReloadMenu(){
+    if type "$CSESSION" &>/dev/null;then  # bl-conky-session script found
+        menuItem "Reload Conkys" "$CSESSION"
+    fi
+}
+
+loadSavedsessionSubmenu(){
+    if type "$CSESSION" &>/dev/null;then  # bl-conky-session script found
+        menuSubmenu "Sessions" "Saved Sessions"
+        getSessions
+        menuSubmenuEnd
+    fi
+}
+
+loadPinMenu(){
+    if type bl-conkypin &>/dev/null;then
+        menuItem "Pin moveable Conkys" "bl-conkypin"
+        menuSeparator
+    fi
+}
+
+loadEditMenu(){
     menuItem "Default conkyrc" "bl-text-editor $CONKYDEFAULT"
     if [[ $(pidof conky) ]];then
         menuSubmenu "RunningConky" "Running Conkys"
-        while read session ;do  # get running conkys from sessionfile
+        while read -r session ;do  # get running conkys from sessionfile
+            [[ -z $session ]] && continue
             CPATH=$(echo "$session" | awk '{print $3}')
             CONKY=$(echo "$CPATH" | awk -F"/" '{print $(NF-1)"/"$NF }')
             menuItem "$CONKY" "bl-text-editor $CPATH"
         done < "$CSESSIONFILE"
         menuSubmenuEnd
-    else 
-        menuItem "No Running Conkys" 
+    else
+        menuItem "No Running Conkys"
     fi
 }
 
 getConkys(){
     menuSubmenu "EditConky" "Edit Conkys"
-        if type bl-conkyedit;then  # bl-conkyedit script found
+        if type bl-conkyedit &>/dev/null;then  # bl-conkyedit script found
             menuItem "Conky Editor" "bl-conkyedit"
-            loadEditmenu
+            loadEditMenu
         else
-            loadEditmenu
+            loadEditMenu
         fi
     menuSubmenuEnd
 }
@@ -72,18 +148,13 @@ checkHelpfile(){
 }
 
 menuStart "Conkymenu" "Conky"
-menuItem "Conky Chooser" "$CZEN"
-menuItem "Reload Conkys" "$CSESSION"
+loadChooserMenu
+loadReloadMenu
 getConkys
-menuSeparator 
-menuItem "Pin moveable Conkys" "bl-conkypin"
-menuSeparator 
-menuItem "New Conky Session" "bl-conkyzen -z"
-menuSubmenu "Sessions" "Saved Sessions"
-getSessions
-menuSubmenuEnd
-menuSeparator 
+menuSeparator
+loadPinMenu
+loadNewsessionMenu
+loadSavedsessionSubmenu
+menuSeparator
 checkHelpfile
 menuEnd
-
-
diff --git a/bin/bl-help-pipemenu b/bin/bl-help-pipemenu
--- a/bin/bl-help-pipemenu
+++ b/bin/bl-help-pipemenu
@@ -1,12 +1,45 @@
 #!/bin/bash
+#    bl-help-pipemenu - an Openbox pipemenu for displaying help files
+#    Copyright (C) 2015 damo    <damo@bunsenlabs.org>
 #
-# bl-help-pipemenu
-# Prepared for BunsenLabs Linux by damo <damo@bunsenlabs.org> March 2015
+#    This program is free software: you can redistribute it and/or modify
+#    it under the terms of the GNU General Public License as published by
+#    the Free Software Foundation, either version 3 of the License, or
+#    (at your option) any later version.
+#
+#    This program is distributed in the hope that it will be useful,
+#    but WITHOUT ANY WARRANTY; without even the implied warranty of
+#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+#    GNU General Public License for more details.
+#
+#    You should have received a copy of the GNU General Public License
+#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-BL_COMMON_LIBDIR='/usr/lib/bunsen/bunsen-common'
+HELP='    bl-help-pipemenu an Openbox Pipe Menu for displaying help files
+    It should normally be called from an openbox menu.
+
+Options (usually passed from the menu):
+    -h --help   show this message
+
+    If bl-help-pipemenu is called with no options (the usual method),
+    it will output an xml openbox pipemenu displaying various help files,
+    both online and on the system.
+'
+# look for a help option somewhere
+for i in "$@"
+do
+    case "$i" in
+    -h|--help)
+        echo "$HELP"
+        exit 0
+        ;;
+    esac
+done
+
+BL_COMMON_LIBDIR='/usr/lib/bunsen/common'
 
 if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
-    echo $"Error: Failed to locate bl-include.cfg in $BL_COMMON_LIBDIR" >&2
+    echo $"Error: Failed to source bl-include.cfg in $BL_COMMON_LIBDIR" >&2
     exit 1
 fi
 
@@ -43,23 +76,22 @@ menuSubmenuEnd
 
 menuSubmenu 'Tint2WWW' 'Tint2'
 menuItem 'Tint2 Wiki: FAQ' 'x-www-browser "https://gitlab.com/o9000/tint2/wikis/FAQ"'
-menuItem 'Tint2 Wiki: Configuration' 'x-www-browser "https://gitlab.com/o9000/tint2/wikis/Configure"'
+menuItem 'Tint2 Wiki: Configuration' 'x-www-browser "https://gitlab.com/o9000/tint2/blob/master/doc/tint2.md"'
 menuItem 'Tint2 Forum Thread' 'x-www-browser "https://forums.bunsenlabs.org/viewtopic.php?id=254"'
 menuItem 'Tint2 man page' 'x-terminal-emulator -T "Tint2 man page" -e man tint2'
 menuSubmenuEnd
 
 menuSubmenu 'ConkyWWW' 'Conky'
-menuItem 'Conky Configuration Settings' 'x-www-browser "http://conky.sourceforge.net/config_settings.html"'
-menuItem 'Conky Variables' 'x-www-browser "http://conky.sourceforge.net/variables.html"'
+menuItem 'Conky Wiki' 'x-www-browser "https://github.com/brndnmtthws/conky/wiki"'
 menuItem 'Conky Archive' 'x-www-browser "http://crunchbang.org/forums/viewtopic.php?pid=371424"'
 menuItem 'Conky man pages' 'x-terminal-emulator -T "Conky man page" -e man conky'
 menuSubmenuEnd
 menuSeparator
 
 menuSubmenu 'ThemesWWW' 'Theme Resources'
+menuItem 'Bunsenlabs on DeviantArt' 'x-www-browser "http://bunsenlabs.deviantart.com/"'
 menuItem 'Box-Look.org' 'x-www-browser "http://www.box-look.org"'
 menuItem 'gnome-look.org' 'x-www-browser "http://gnome-look.org/"'
-menuItem 'DeviantArt' 'x-www-browser "http://www.deviantart.com/browse/all/"'
 menuSubmenuEnd
 menuSeparator
 menuSeparator 'man pages'
@@ -68,5 +100,11 @@ menuItem 'dmenu' 'x-terminal-emulator -T "dmenu man page" -e man dmenu'
 menuItem 'gmrun' 'x-terminal-emulator -T "gmrun man page" -e man gmrun'
 menuItem 'xrandr' 'x-terminal-emulator -T "xrandr man page" -e man xrandr'
 
+menuSeparator
+menuSubmenu 'BLhelp' 'Bunsen Help Files'
+menuItem 'How to Edit Menu' 'yad --button="OK":0 --center --window-icon=distributor-logo-bunsenlabs --text-info --title="How to Edit the Menu" --filename="/usr/share/bunsen/docs/helpfile-menu.txt" --width=900 --height=700 --fontname=Monospace'
+menuItem 'About Bunsen Alternatives' 'yad --button="OK":0 --center --window-icon=distributor-logo-bunsenlabs --text-info --title="About Bunsen Alternatives" --filename="/usr/share/bunsen/docs/helpfile-bl-alternatives.txt" --width=900 --height=700 --fontname=Monospace'
+menuItem 'Conkyzen Help' 'yad --button="OK":0 --center --window-icon=distributor-logo-bunsenlabs --text-info --title="Conkyzen Help" --filename="/usr/share/bunsen/docs/helpfile-conkyzen.txt" --width=900 --height=700 --fontname=Monospace'
+menuSubmenuEnd
 
 menuEnd
diff --git a/bin/bl-printing-pipemenu b/bin/bl-printing-pipemenu
--- a/bin/bl-printing-pipemenu
+++ b/bin/bl-printing-pipemenu
@@ -1,14 +1,48 @@
 #!/bin/bash
-# ---------------------------------------------------------------------
-# An Openbox pipemenu for configuring printing under Bunsen labs Linux.
-# Originally written for CrunchBang Linux <http://crunchbanglinux.org/>
-# by Philip Newborough (aka corenominal) <mail@philipnewborough.co.uk>
-# ---------------------------------------------------------------------
+#    bl-printing-pipemenu an Openbox pipemenu for configuring printing
+#    Copyright (C) 2012 Philip Newborough   <corenominal@corenominal.org>
+#    Copyright (C) 2013 Aleks-Daniel Jakimenko
+#    Copyright (C) 2015 John Crawley    <john@bunsenlabs.org>
+#
+#    This program is free software: you can redistribute it and/or modify
+#    it under the terms of the GNU General Public License as published by
+#    the Free Software Foundation, either version 3 of the License, or
+#    (at your option) any later version.
+#
+#    This program is distributed in the hope that it will be useful,
+#    but WITHOUT ANY WARRANTY; without even the implied warranty of
+#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+#    GNU General Public License for more details.
+#
+#    You should have received a copy of the GNU General Public License
+#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-BL_COMMON_LIBDIR='/usr/lib/bunsen/bunsen-common'
+HELP='    bl-printing-pipemenu an Openbox Pipe Menu for configuring printing
+    It should normally be called from an openbox menu.
+
+Options (usually passed from the menu):
+    -h --help   show this message
+    --install   install printing support
+
+    If bl-printing-pipemenu is called with no options (the usual method),
+    it will output an xml openbox pipemenu
+    for installing printing support and configuring printing.
+'
+# look for a help option somewhere
+for i in "$@"
+do
+    case "$i" in
+    -h|--help)
+        echo "$HELP"
+        exit 0
+        ;;
+    esac
+done
+
+BL_COMMON_LIBDIR='/usr/lib/bunsen/common'
 
 if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
-    echo $"Error: Failed to locate bl-include.cfg in $BL_COMMON_LIBDIR" >&2
+    echo $"Error: Failed to source bl-include.cfg in $BL_COMMON_LIBDIR" >&2
     exit 1
 fi
 
@@ -16,7 +50,7 @@ if [[ $1 = '--install' ]]; then
 
     terminalCheck -T 'Install Printer Support' --install
 
-    promptInstall 'PRINTING SUPPORT' 'This script will install printing support.' 'bl-meta-printer-support'
+    promptInstall 'PRINTING SUPPORT' 'This script will install printing support.' 'bunsen-meta-printer-support'
 
 elif [[ $1 ]]; then
     echo "$0: no such option $*" >&2
diff --git a/bin/bl-x-www-browser-pipemenu b/bin/bl-x-www-browser-pipemenu
--- a/bin/bl-x-www-browser-pipemenu
+++ b/bin/bl-x-www-browser-pipemenu
@@ -1,31 +1,65 @@
 #!/bin/bash
-# ---------------------------------------------------------------------
-# A pipemenu to install a browser on Bunsen Labs Linux.
+#    bl-x-www-browser-pipemenu - an Openbox pipemenu for web browsers
+#    Copyright (C) 2012 Philip Newborough   <corenominal@corenominal.org>
+#    Copyright (C) 2013 Aleks-Daniel Jakimenko
+#    Copyright (C) 2015 damo    <damo@bunsenlabs.org>
+#    Copyright (C) 2015-2016 John Crawley    <john@bunsenlabs.org>
 #
-# Originally written for CrunchBang Linux <http://crunchbang.org/>
-# by Philip Newborough (aka corenominal) <corenominal@corenominal.org>
+#    This program is free software: you can redistribute it and/or modify
+#    it under the terms of the GNU General Public License as published by
+#    the Free Software Foundation, either version 3 of the License, or
+#    (at your option) any later version.
 #
-# Modified by damo <damo@bunsenlabs.org> for BunsenLabs Linux   April 2015
+#    This program is distributed in the hope that it will be useful,
+#    but WITHOUT ANY WARRANTY; without even the implied warranty of
+#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+#    GNU General Public License for more details.
 #
+#    You should have received a copy of the GNU General Public License
+#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
+
 #   To change the entries shown in the Browsers pipemenu:
 #   edit ".config/openbox/pipemenus.rc"
-#
-# ---------------------------------------------------------------------
 
-BL_COMMON_LIBDIR='/usr/lib/bunsen/bunsen-common'
+HELP='    bl-x-www-browser-pipemenu an Openbox Pipe Menu for web browsers
+    It should normally be called from an openbox menu.
+
+Options (usually passed from the menu):
+    -h --help   show this message
+    --install   install a web browser
+    (the browser must be in the list defined in the pipemenu config file)
+    (NOTE: Google Chrome will not appear in the menu on 32bit systems.)
+
+    If bl-x-www-browser-pipemenu is called with no options (the usual method),
+    it will output an xml openbox pipemenu
+    for launching and installing web browsers.
+
+See ~/.config/openbox/pipemenus.rc for configuration options.
+'
+# look for a help option somewhere
+for i in "$@"
+do
+    case "$i" in
+    -h|--help)
+        echo "$HELP"
+        exit 0
+        ;;
+    esac
+done
+
+BL_COMMON_LIBDIR='/usr/lib/bunsen/common'
 USR_CFG_DIR="$HOME/.config/openbox"
-
-# If the package needs additional configuration before installation
-# create a function called setupBrowserName, it will be called automatically.
 
 KEY_URLS_GOOGLE=('https://dl-ssl.google.com/linux/linux_signing_key.pub')
 KEY_URLS_OPERA=('http://deb.opera.com/archive.key')
 
+declareDependencies wget
+
 if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
-    echo $"Error: Failed to locate bl-include.cfg in $BL_COMMON_LIBDIR" >&2
+    echo $"Error: Failed to source bl-include.cfg in $BL_COMMON_LIBDIR" >&2
     exit 1
 elif ! . "$USR_CFG_DIR/pipemenus.rc" 2> /dev/null; then
-    echo $"Error: Failed to locate pipemenus.rc in $USR_CFG_DIR" >&2
+    echo $"Error: Failed to source pipemenus.rc in $USR_CFG_DIR" >&2
     exit 1
 fi
 
@@ -69,6 +103,9 @@ addAptKey() {
     return 0
 }
 
+# If the package needs additional configuration before installation
+# create a function called setupBrowserName, it will be called automatically.
+
 setupGoogleChromeStable() {
     addAptKey "${KEY_URLS_GOOGLE[@]}" || return 1
     say 'Creating APT sources file...' 1
@@ -90,6 +127,7 @@ if [[ $1 = --install ]]; then
 
     desc="This script will install the $appName browser."
     setupFunctionName="setup${appName//[^a-zA-Z]/}" # setupFunctionName should now be in format like 'setupChromium'
+    [[ $packageName = firefox ]] && packageName='firefox-esr' # firefox in Debian Jessie
     if [[ $(type -t "$setupFunctionName") = 'function' ]]; then
         promptInstall --setup "$setupFunctionName" "$appName" "$desc" "$packageName"
     else
@@ -115,7 +153,8 @@ else # pipemenu
     done
     menu_started=false
     for curApp in "${BROWSERS[@]}"; do
-        if ! [[ ${AppStatus[$curApp]} = installed ]]; then
+        if [[ ${AppStatus[$curApp]} != installed ]]; then
+            [[ $curApp = google-chrome-stable && $(dpkg --print-architecture) != 'amd64' ]] && continue
             $menu_started || menuSubmenu "browsers-install-submenu" "Install"
             menu_started=true
             menuItem "Install ${AppName[$curApp]}" "$0 --install $curApp"
@@ -125,7 +164,7 @@ else # pipemenu
 
     if $INSTALLED ; then
         menuSeparator
-        menuItem 'Select Default Browser' "x-terminal-emulator -T 'Select Default Browser' -e sudo update-alternatives --config x-www-browser"
+        menuItem 'Select Default Browser' "x-terminal-emulator -T 'Select Default Browser' -e sh -c 'sudo update-alternatives --config x-www-browser; sleep 5'"
     fi
     menuEnd
 fi
